### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/julia#1]
_Note: the launch checklist has been made obsolete by a brand new Launch Guide: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md_

Let's keep the general discussions around what needs to be done here in this issue, and open new, actionable issues for next steps.

**Comment by kytrinyx** [comment]
@SaschaMann Would you be interested in having commit on this track? Your contributions to date are much appreciated! You would be expected to do as little or as much as you like.

We have some documentation about what often goes into maintaining language tracks: https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md

Anyway—let me know (and if you want to ask me things privately, feel free to send me an email. My address is on my GitHub profile page).

**Comment by SaschaMann** [comment]
@kytrinyx Thanks for going through the PRs! I'd like to help maintain this track and get it started. :) I've read the doc you linked as well as the contributing guide.

I think once it gets running, there will be more people willing to help out as mentors etc. as well.

Now that there's a test suite, could you turn on Travis for this track?

**Comment by petertseng** [comment]
Hello, just dropping in to say I'm happy the track has a maintainer. I don't know Julia at all, but was interested in learning. Therefore, it would be good if there were exercises. Someday, maybe I will even add one as well...!

**Comment by kytrinyx** [comment]
@SaschaMann yay, awesome! I've created a team for Julia, and invited you to it. I also invited you to the exercism/track-maintainers team, which has commit on the x-common repo where the shared problem metadata lives.

I've also turned on CI for the track.

**Comment by SaschaMann** [comment]
We've passed the 10 problem milestone, thanks to @andrej-makarov-skrt's contributions! 🎉

Nice to see so much progress on this track in the last two weeks :)

**Comment by SaschaMann** [comment]
@andrej-makarov-skrt would you be willing to join as a maintainer as well? Your work so far is very much appreciated.

I'm just gonna copy @kytrinyx info about it:
>You would be expected to do as little or as much as you like.
>We have some documentation about what often goes into maintaining language tracks: https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md

**Comment by andrej-makarov-skrt** [comment]
@SaschaMann yes, I would try. Thank you!

**Comment by kytrinyx** [comment]
🎉 Thank you @andrej-makarov-skrt, that's great news. I've invited you to the exercism/julia and exercism/track-maintainers teams.

**Comment by SaschaMann** [comment]
PR #30 made me aware of another issue that could come up quite frequently on this track: Which versions of Julia should be supported? Before a v1.0 is available, there will be plenty of breaking changes that will break test suites and example solutions.

Imo switching immediately to a new stable release would be good in order to provide exercises for the latest version. The code could be prepared beforehand with the RC builds and just merged shortly after the release.

However, this could lead to a lot of frustration if JuliaPro or the binaries available through package managers aren't updated as quickly. It would also require users to be aware that a new Julia version came out and what changed.

Submitted solution may also differ depending on the version/time it was written. So if someone looks at other solutions, it could cause some confusion.

@kytrinyx Could you provide some insight on how other tracks handle this?

---

Unrelated: Could you add me as a track mentor for Julia on the exercism website, please? I saw that some people already submitted solutions and it would be good to give feedback & see if they encounter any issues. I'll try to find some more track mentors on Gitter etc, too.

**Comment by kytrinyx** [comment]
@SaschaMann We tend to optimize for the "recent stable" (whatever is easy to get your hands on) in the documentation / what we suggest people use, and then we have CI test on the edge so that we're aware of potential failures and conflicts as early as possible.

**Comment by kytrinyx** [comment]
> Could you add me as a track mentor for Julia on the exercism website, please?

@SaschaMann Ah, yepp. Doing that now.

**Comment by SaschaMann** [comment]
Aside from the issue of finding track mentors, the track is pretty much ready to launch and as far as I can tell most of the necessary updates for nextercism have been done as well.

I don't have time to spend on searching mentors, but perhaps with the better visibility of being "launched" and not just "upcoming" anymore, some willing people might find it.

**Comment by kytrinyx** [comment]
Yes! I think we should ship it. We're going to do some planning around mentors "globally" so to speak, which should help all the tracks.

**Comment by SaschaMann** [comment]
I've switched it on #88
