### ISSUE TITLE
Still getting `Base.Test` in test code.

### ISSUE THREAD

**Issue by tmccombs** [exercism/julia#128]
I'm really confused by this. In this repo all the test code uses `use Test` instead of `use Base.Test`, but when I download exercises, my `runtest.jl` starts with `use Base.Test`, and `use Base.Test` also shows up in the "Test Suite" section of the exercise on the website.

**Comment by SaschaMann** [comment]
This likely happens due to: https://github.com/exercism/exercism/issues/4219

Unfortunately there isn't anything we can do about it on the Julia track itself, so I'll close this. There are some suggested workarounds in the linked issue. It bothers me, too, because changes won't even reach many of the students.

**Comment by SaschaMann** [comment]
@tmccombs just fyi, this has been fixed and you should now see a button to update the test suite to the latest version on the website.
