### ISSUE TITLE
Exercises are listed on website despite not being in `config.json` nor `exercises/concept`

### ISSUE THREAD

**Issue by SaschaMann** [exercism/julia#608]
![grafik](https://user-images.githubusercontent.com/20866761/227061094-7c646433-3a1e-48bb-99e5-ed6b2db0a45f.png)

These aren't in config.json, nor in `exercises/concept` apart from lasagna. Is it possible that `concept.wip` is parsed incorrectly? Or am I missing something?

**Comment by SaschaMann** [comment]
Somehow, leap exists thrice: 
![grafik](https://user-images.githubusercontent.com/20866761/227061354-6707dda6-c745-48e8-a451-d5416004afff.png)

**Comment by ErikSchierboom** [comment]
I'm positive we don't parse the wip `config.json` file. The reason the exercises are all listed is because:

1. They were once in the `config.json` file (see https://github.com/exercism/julia/commit/9afbde562272688dea3e6fee0d8fae1301c38bea#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cf)
2. We don't support deleting exercises, only deprecating (so they aren't removed)
3. You're a maintainer so you see all exercises

**Comment by ErikSchierboom** [comment]
The `leap` thing is weird, but likely due to it re-using the same slug (another reason why we don't want to re-use the exercises). If you've ever done the `leap` practice exercise, deprecating it will still result in it being shown.

**Comment by SaschaMann** [comment]
Ahh okay. I didn't know that it'd not remove them.
